#include "ZDOID.h"

decltype(ZDOID::NONE) ZDOID::NONE = ZDOID();

/*
decltype(ZDOID::INDEXED_USERS) ZDOID::INDEXED_USERS;
decltype(ZDOID::NEXT_EMPTY_INDEX) ZDOID::NEXT_EMPTY_INDEX = 1;
decltype(ZDOID::LAST_SET_INDEX) ZDOID::LAST_SET_INDEX = 1;
*/